apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pmotrack
type: Opaque
stringData:
  POSTGRES_DB: "redmine_db"
  POSTGRES_USER: "redmine_user"
  POSTGRES_PASSWORD: "RedminePassword123!"
